# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'postApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  use_frameworks!

  # Pods for postApp

end
